name: Update SVG

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-uptime:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil lxml requests
        
    - name: Run update script
      run: python kachow.py
      env:
        README_TOKEN: ${{ secrets.README_TOKEN }}
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dark.svg light.svg
        git diff --staged --quiet || git commit -m "update(svg): $(date '+%Y-%m-%d')"
        git push
